package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author user
 * @date 2024/05/19 13:57:46
 * akibaheadoffice 社員テーブル
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Akibaheadoffice implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column akibaheadoffice.id
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    /**
     * @TableNameakibaheadoffice
     * @TableRemarks 社員テーブル
     * @ActualColumnName id
     * @ActualColumnRemarks NO
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column akibaheadoffice.name
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    /**
     * @TableNameakibaheadoffice
     * @TableRemarks 社員テーブル
     * @ActualColumnName name
     * @ActualColumnRemarks 名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 200
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column akibaheadoffice.salary
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    /**
     * @TableNameakibaheadoffice
     * @TableRemarks 社員テーブル
     * @ActualColumnName salary
     * @ActualColumnRemarks 給料
     * @ActualTypeName DOUBLE
     * @isNullable true
     * @Length 10
     * @Scale 2
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName DOUBLE
     * @JdbcType 8
     */
    private Double salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column akibaheadoffice.birthday
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    /**
     * @TableNameakibaheadoffice
     * @TableRemarks 社員テーブル
     * @ActualColumnName birthday
     * @ActualColumnRemarks 年月日
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column akibaheadoffice.photo
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    /**
     * @TableNameakibaheadoffice
     * @TableRemarks 社員テーブル
     * @ActualColumnName photo
     * @ActualColumnRemarks アイコン
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 200
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column akibaheadoffice.sex
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    /**
     * @TableNameakibaheadoffice
     * @TableRemarks 社員テーブル
     * @ActualColumnName sex
     * @ActualColumnRemarks 性別
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column akibaheadoffice.roster
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    /**
     * @TableNameakibaheadoffice
     * @TableRemarks 社員テーブル
     * @ActualColumnName roster
     * @ActualColumnRemarks 勤務表
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 255
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String roster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column akibaheadoffice.position
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    /**
     * @TableNameakibaheadoffice
     * @TableRemarks 社員テーブル
     * @ActualColumnName position
     * @ActualColumnRemarks 職位
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column akibaheadoffice.history
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    /**
     * @TableNameakibaheadoffice
     * @TableRemarks 社員テーブル
     * @ActualColumnName history
     * @ActualColumnRemarks 履歴
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String history;
}