package com.baizhi.entity.original;

import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @author admin
 * @date 2024/11/25 11:31:52
 * m_code 
 */
@Accessors(chain = true)
@Data
public class MCodeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_code.m_key
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamem_code
     * @TableRemarks 
     * @ActualColumnName m_key
     * @ActualColumnRemarks 
     * @ActualTypeName VARCHAR
     * @isNullable false
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String mKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_code.m_code
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamem_code
     * @TableRemarks 
     * @ActualColumnName m_code
     * @ActualColumnRemarks 
     * @ActualTypeName CHAR
     * @isNullable false
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String mCode;
}