package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author user
 * @date 2023/10/09 20:43:16
 * m_code m_code
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MCode extends MCodeKey implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_code.value
     *
     * @mbg.generated Mon Oct 09 20:43:16 JST 2023
     */
    /**
     * @TableNamem_code
     * @TableRemarks m_code
     * @ActualColumnName value
     * @ActualColumnRemarks value
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 50
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_code.delete_flg
     *
     * @mbg.generated Mon Oct 09 20:43:16 JST 2023
     */
    /**
     * @TableNamem_code
     * @TableRemarks m_code
     * @ActualColumnName delete_flg
     * @ActualColumnRemarks 削除フラグ
     * @ActualTypeName CHAR
     * @isNullable false
     * @Length 1
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_code.create_time
     *
     * @mbg.generated Mon Oct 09 20:43:16 JST 2023
     */
    /**
     * @TableNamem_code
     * @TableRemarks m_code
     * @ActualColumnName create_time
     * @ActualColumnRemarks 登録日時
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_code.create_user_id
     *
     * @mbg.generated Mon Oct 09 20:43:16 JST 2023
     */
    /**
     * @TableNamem_code
     * @TableRemarks m_code
     * @ActualColumnName create_user_id
     * @ActualColumnRemarks 登録者
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_code.update_time
     *
     * @mbg.generated Mon Oct 09 20:43:16 JST 2023
     */
    /**
     * @TableNamem_code
     * @TableRemarks m_code
     * @ActualColumnName update_time
     * @ActualColumnRemarks 更新日時
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_code.update_user_id
     *
     * @mbg.generated Mon Oct 09 20:43:16 JST 2023
     */
    /**
     * @TableNamem_code
     * @TableRemarks m_code
     * @ActualColumnName update_user_id
     * @ActualColumnRemarks 更新者
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String updateUserId;
}