package com.baizhi.entity.original;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @author user
 * @date 2024/02/15 17:26:08
 * m_code マスタコード
 */
@Accessors(chain = true)
@Data
@Builder
@AllArgsConstructor
public class MCodeExample implements java.io.Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public MCodeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMKeyIsNull() {
            addCriterion("m_key is null");
            return (Criteria) this;
        }

        public Criteria andMKeyIsNotNull() {
            addCriterion("m_key is not null");
            return (Criteria) this;
        }

        public Criteria andMKeyEqualTo(String value) {
            addCriterion("m_key =", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyNotEqualTo(String value) {
            addCriterion("m_key <>", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyGreaterThan(String value) {
            addCriterion("m_key >", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyGreaterThanOrEqualTo(String value) {
            addCriterion("m_key >=", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyLessThan(String value) {
            addCriterion("m_key <", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyLessThanOrEqualTo(String value) {
            addCriterion("m_key <=", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyLike(String value) {
            addCriterion("m_key like", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyNotLike(String value) {
            addCriterion("m_key not like", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyIn(List<String> values) {
            addCriterion("m_key in", values, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyNotIn(List<String> values) {
            addCriterion("m_key not in", values, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyBetween(String value1, String value2) {
            addCriterion("m_key between", value1, value2, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyNotBetween(String value1, String value2) {
            addCriterion("m_key not between", value1, value2, "mKey");
            return (Criteria) this;
        }

        public Criteria andMCodeIsNull() {
            addCriterion("m_code is null");
            return (Criteria) this;
        }

        public Criteria andMCodeIsNotNull() {
            addCriterion("m_code is not null");
            return (Criteria) this;
        }

        public Criteria andMCodeEqualTo(String value) {
            addCriterion("m_code =", value, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeNotEqualTo(String value) {
            addCriterion("m_code <>", value, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeGreaterThan(String value) {
            addCriterion("m_code >", value, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeGreaterThanOrEqualTo(String value) {
            addCriterion("m_code >=", value, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeLessThan(String value) {
            addCriterion("m_code <", value, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeLessThanOrEqualTo(String value) {
            addCriterion("m_code <=", value, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeLike(String value) {
            addCriterion("m_code like", value, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeNotLike(String value) {
            addCriterion("m_code not like", value, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeIn(List<String> values) {
            addCriterion("m_code in", values, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeNotIn(List<String> values) {
            addCriterion("m_code not in", values, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeBetween(String value1, String value2) {
            addCriterion("m_code between", value1, value2, "mCode");
            return (Criteria) this;
        }

        public Criteria andMCodeNotBetween(String value1, String value2) {
            addCriterion("m_code not between", value1, value2, "mCode");
            return (Criteria) this;
        }

        public Criteria andMValueIsNull() {
            addCriterion("m_value is null");
            return (Criteria) this;
        }

        public Criteria andMValueIsNotNull() {
            addCriterion("m_value is not null");
            return (Criteria) this;
        }

        public Criteria andMValueEqualTo(String value) {
            addCriterion("m_value =", value, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueNotEqualTo(String value) {
            addCriterion("m_value <>", value, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueGreaterThan(String value) {
            addCriterion("m_value >", value, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueGreaterThanOrEqualTo(String value) {
            addCriterion("m_value >=", value, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueLessThan(String value) {
            addCriterion("m_value <", value, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueLessThanOrEqualTo(String value) {
            addCriterion("m_value <=", value, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueLike(String value) {
            addCriterion("m_value like", value, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueNotLike(String value) {
            addCriterion("m_value not like", value, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueIn(List<String> values) {
            addCriterion("m_value in", values, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueNotIn(List<String> values) {
            addCriterion("m_value not in", values, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueBetween(String value1, String value2) {
            addCriterion("m_value between", value1, value2, "mValue");
            return (Criteria) this;
        }

        public Criteria andMValueNotBetween(String value1, String value2) {
            addCriterion("m_value not between", value1, value2, "mValue");
            return (Criteria) this;
        }

        public Criteria andMOrderIsNull() {
            addCriterion("m_order is null");
            return (Criteria) this;
        }

        public Criteria andMOrderIsNotNull() {
            addCriterion("m_order is not null");
            return (Criteria) this;
        }

        public Criteria andMOrderEqualTo(Integer value) {
            addCriterion("m_order =", value, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMOrderNotEqualTo(Integer value) {
            addCriterion("m_order <>", value, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMOrderGreaterThan(Integer value) {
            addCriterion("m_order >", value, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("m_order >=", value, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMOrderLessThan(Integer value) {
            addCriterion("m_order <", value, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMOrderLessThanOrEqualTo(Integer value) {
            addCriterion("m_order <=", value, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMOrderIn(List<Integer> values) {
            addCriterion("m_order in", values, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMOrderNotIn(List<Integer> values) {
            addCriterion("m_order not in", values, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMOrderBetween(Integer value1, Integer value2) {
            addCriterion("m_order between", value1, value2, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("m_order not between", value1, value2, "mOrder");
            return (Criteria) this;
        }

        public Criteria andMDisplay1IsNull() {
            addCriterion("m_display1 is null");
            return (Criteria) this;
        }

        public Criteria andMDisplay1IsNotNull() {
            addCriterion("m_display1 is not null");
            return (Criteria) this;
        }

        public Criteria andMDisplay1EqualTo(String value) {
            addCriterion("m_display1 =", value, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1NotEqualTo(String value) {
            addCriterion("m_display1 <>", value, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1GreaterThan(String value) {
            addCriterion("m_display1 >", value, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1GreaterThanOrEqualTo(String value) {
            addCriterion("m_display1 >=", value, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1LessThan(String value) {
            addCriterion("m_display1 <", value, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1LessThanOrEqualTo(String value) {
            addCriterion("m_display1 <=", value, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1Like(String value) {
            addCriterion("m_display1 like", value, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1NotLike(String value) {
            addCriterion("m_display1 not like", value, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1In(List<String> values) {
            addCriterion("m_display1 in", values, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1NotIn(List<String> values) {
            addCriterion("m_display1 not in", values, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1Between(String value1, String value2) {
            addCriterion("m_display1 between", value1, value2, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay1NotBetween(String value1, String value2) {
            addCriterion("m_display1 not between", value1, value2, "mDisplay1");
            return (Criteria) this;
        }

        public Criteria andMDisplay2IsNull() {
            addCriterion("m_display2 is null");
            return (Criteria) this;
        }

        public Criteria andMDisplay2IsNotNull() {
            addCriterion("m_display2 is not null");
            return (Criteria) this;
        }

        public Criteria andMDisplay2EqualTo(String value) {
            addCriterion("m_display2 =", value, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2NotEqualTo(String value) {
            addCriterion("m_display2 <>", value, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2GreaterThan(String value) {
            addCriterion("m_display2 >", value, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2GreaterThanOrEqualTo(String value) {
            addCriterion("m_display2 >=", value, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2LessThan(String value) {
            addCriterion("m_display2 <", value, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2LessThanOrEqualTo(String value) {
            addCriterion("m_display2 <=", value, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2Like(String value) {
            addCriterion("m_display2 like", value, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2NotLike(String value) {
            addCriterion("m_display2 not like", value, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2In(List<String> values) {
            addCriterion("m_display2 in", values, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2NotIn(List<String> values) {
            addCriterion("m_display2 not in", values, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2Between(String value1, String value2) {
            addCriterion("m_display2 between", value1, value2, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay2NotBetween(String value1, String value2) {
            addCriterion("m_display2 not between", value1, value2, "mDisplay2");
            return (Criteria) this;
        }

        public Criteria andMDisplay3IsNull() {
            addCriterion("m_display3 is null");
            return (Criteria) this;
        }

        public Criteria andMDisplay3IsNotNull() {
            addCriterion("m_display3 is not null");
            return (Criteria) this;
        }

        public Criteria andMDisplay3EqualTo(String value) {
            addCriterion("m_display3 =", value, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3NotEqualTo(String value) {
            addCriterion("m_display3 <>", value, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3GreaterThan(String value) {
            addCriterion("m_display3 >", value, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3GreaterThanOrEqualTo(String value) {
            addCriterion("m_display3 >=", value, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3LessThan(String value) {
            addCriterion("m_display3 <", value, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3LessThanOrEqualTo(String value) {
            addCriterion("m_display3 <=", value, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3Like(String value) {
            addCriterion("m_display3 like", value, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3NotLike(String value) {
            addCriterion("m_display3 not like", value, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3In(List<String> values) {
            addCriterion("m_display3 in", values, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3NotIn(List<String> values) {
            addCriterion("m_display3 not in", values, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3Between(String value1, String value2) {
            addCriterion("m_display3 between", value1, value2, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay3NotBetween(String value1, String value2) {
            addCriterion("m_display3 not between", value1, value2, "mDisplay3");
            return (Criteria) this;
        }

        public Criteria andMDisplay4IsNull() {
            addCriterion("m_display4 is null");
            return (Criteria) this;
        }

        public Criteria andMDisplay4IsNotNull() {
            addCriterion("m_display4 is not null");
            return (Criteria) this;
        }

        public Criteria andMDisplay4EqualTo(String value) {
            addCriterion("m_display4 =", value, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4NotEqualTo(String value) {
            addCriterion("m_display4 <>", value, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4GreaterThan(String value) {
            addCriterion("m_display4 >", value, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4GreaterThanOrEqualTo(String value) {
            addCriterion("m_display4 >=", value, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4LessThan(String value) {
            addCriterion("m_display4 <", value, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4LessThanOrEqualTo(String value) {
            addCriterion("m_display4 <=", value, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4Like(String value) {
            addCriterion("m_display4 like", value, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4NotLike(String value) {
            addCriterion("m_display4 not like", value, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4In(List<String> values) {
            addCriterion("m_display4 in", values, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4NotIn(List<String> values) {
            addCriterion("m_display4 not in", values, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4Between(String value1, String value2) {
            addCriterion("m_display4 between", value1, value2, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay4NotBetween(String value1, String value2) {
            addCriterion("m_display4 not between", value1, value2, "mDisplay4");
            return (Criteria) this;
        }

        public Criteria andMDisplay5IsNull() {
            addCriterion("m_display5 is null");
            return (Criteria) this;
        }

        public Criteria andMDisplay5IsNotNull() {
            addCriterion("m_display5 is not null");
            return (Criteria) this;
        }

        public Criteria andMDisplay5EqualTo(String value) {
            addCriterion("m_display5 =", value, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5NotEqualTo(String value) {
            addCriterion("m_display5 <>", value, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5GreaterThan(String value) {
            addCriterion("m_display5 >", value, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5GreaterThanOrEqualTo(String value) {
            addCriterion("m_display5 >=", value, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5LessThan(String value) {
            addCriterion("m_display5 <", value, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5LessThanOrEqualTo(String value) {
            addCriterion("m_display5 <=", value, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5Like(String value) {
            addCriterion("m_display5 like", value, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5NotLike(String value) {
            addCriterion("m_display5 not like", value, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5In(List<String> values) {
            addCriterion("m_display5 in", values, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5NotIn(List<String> values) {
            addCriterion("m_display5 not in", values, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5Between(String value1, String value2) {
            addCriterion("m_display5 between", value1, value2, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay5NotBetween(String value1, String value2) {
            addCriterion("m_display5 not between", value1, value2, "mDisplay5");
            return (Criteria) this;
        }

        public Criteria andMDisplay6IsNull() {
            addCriterion("m_display6 is null");
            return (Criteria) this;
        }

        public Criteria andMDisplay6IsNotNull() {
            addCriterion("m_display6 is not null");
            return (Criteria) this;
        }

        public Criteria andMDisplay6EqualTo(String value) {
            addCriterion("m_display6 =", value, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6NotEqualTo(String value) {
            addCriterion("m_display6 <>", value, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6GreaterThan(String value) {
            addCriterion("m_display6 >", value, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6GreaterThanOrEqualTo(String value) {
            addCriterion("m_display6 >=", value, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6LessThan(String value) {
            addCriterion("m_display6 <", value, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6LessThanOrEqualTo(String value) {
            addCriterion("m_display6 <=", value, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6Like(String value) {
            addCriterion("m_display6 like", value, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6NotLike(String value) {
            addCriterion("m_display6 not like", value, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6In(List<String> values) {
            addCriterion("m_display6 in", values, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6NotIn(List<String> values) {
            addCriterion("m_display6 not in", values, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6Between(String value1, String value2) {
            addCriterion("m_display6 between", value1, value2, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay6NotBetween(String value1, String value2) {
            addCriterion("m_display6 not between", value1, value2, "mDisplay6");
            return (Criteria) this;
        }

        public Criteria andMDisplay7IsNull() {
            addCriterion("m_display7 is null");
            return (Criteria) this;
        }

        public Criteria andMDisplay7IsNotNull() {
            addCriterion("m_display7 is not null");
            return (Criteria) this;
        }

        public Criteria andMDisplay7EqualTo(String value) {
            addCriterion("m_display7 =", value, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7NotEqualTo(String value) {
            addCriterion("m_display7 <>", value, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7GreaterThan(String value) {
            addCriterion("m_display7 >", value, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7GreaterThanOrEqualTo(String value) {
            addCriterion("m_display7 >=", value, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7LessThan(String value) {
            addCriterion("m_display7 <", value, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7LessThanOrEqualTo(String value) {
            addCriterion("m_display7 <=", value, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7Like(String value) {
            addCriterion("m_display7 like", value, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7NotLike(String value) {
            addCriterion("m_display7 not like", value, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7In(List<String> values) {
            addCriterion("m_display7 in", values, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7NotIn(List<String> values) {
            addCriterion("m_display7 not in", values, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7Between(String value1, String value2) {
            addCriterion("m_display7 between", value1, value2, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay7NotBetween(String value1, String value2) {
            addCriterion("m_display7 not between", value1, value2, "mDisplay7");
            return (Criteria) this;
        }

        public Criteria andMDisplay8IsNull() {
            addCriterion("m_display8 is null");
            return (Criteria) this;
        }

        public Criteria andMDisplay8IsNotNull() {
            addCriterion("m_display8 is not null");
            return (Criteria) this;
        }

        public Criteria andMDisplay8EqualTo(String value) {
            addCriterion("m_display8 =", value, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8NotEqualTo(String value) {
            addCriterion("m_display8 <>", value, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8GreaterThan(String value) {
            addCriterion("m_display8 >", value, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8GreaterThanOrEqualTo(String value) {
            addCriterion("m_display8 >=", value, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8LessThan(String value) {
            addCriterion("m_display8 <", value, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8LessThanOrEqualTo(String value) {
            addCriterion("m_display8 <=", value, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8Like(String value) {
            addCriterion("m_display8 like", value, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8NotLike(String value) {
            addCriterion("m_display8 not like", value, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8In(List<String> values) {
            addCriterion("m_display8 in", values, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8NotIn(List<String> values) {
            addCriterion("m_display8 not in", values, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8Between(String value1, String value2) {
            addCriterion("m_display8 between", value1, value2, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay8NotBetween(String value1, String value2) {
            addCriterion("m_display8 not between", value1, value2, "mDisplay8");
            return (Criteria) this;
        }

        public Criteria andMDisplay9IsNull() {
            addCriterion("m_display9 is null");
            return (Criteria) this;
        }

        public Criteria andMDisplay9IsNotNull() {
            addCriterion("m_display9 is not null");
            return (Criteria) this;
        }

        public Criteria andMDisplay9EqualTo(String value) {
            addCriterion("m_display9 =", value, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9NotEqualTo(String value) {
            addCriterion("m_display9 <>", value, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9GreaterThan(String value) {
            addCriterion("m_display9 >", value, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9GreaterThanOrEqualTo(String value) {
            addCriterion("m_display9 >=", value, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9LessThan(String value) {
            addCriterion("m_display9 <", value, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9LessThanOrEqualTo(String value) {
            addCriterion("m_display9 <=", value, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9Like(String value) {
            addCriterion("m_display9 like", value, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9NotLike(String value) {
            addCriterion("m_display9 not like", value, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9In(List<String> values) {
            addCriterion("m_display9 in", values, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9NotIn(List<String> values) {
            addCriterion("m_display9 not in", values, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9Between(String value1, String value2) {
            addCriterion("m_display9 between", value1, value2, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andMDisplay9NotBetween(String value1, String value2) {
            addCriterion("m_display9 not between", value1, value2, "mDisplay9");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("delete_flg is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("delete_flg is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(String value) {
            addCriterion("delete_flg =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(String value) {
            addCriterion("delete_flg <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(String value) {
            addCriterion("delete_flg >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
            addCriterion("delete_flg >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(String value) {
            addCriterion("delete_flg <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
            addCriterion("delete_flg <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLike(String value) {
            addCriterion("delete_flg like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotLike(String value) {
            addCriterion("delete_flg not like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<String> values) {
            addCriterion("delete_flg in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<String> values) {
            addCriterion("delete_flg not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(String value1, String value2) {
            addCriterion("delete_flg between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(String value1, String value2) {
            addCriterion("delete_flg not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_code
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 15 17:26:08 JST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_code
     *
     * @mbg.generated Thu Feb 15 17:26:08 JST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}