package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author miniw
 * @date 2025/01/18 16:23:43
 * m_densya_eki 電車駅テーブル
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MDensyaEki extends MDensyaEkiKey implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_densya_eki.eki_name
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    /**
     * @TableNamem_densya_eki
     * @TableRemarks 電車駅テーブル
     * @ActualColumnName eki_name
     * @ActualColumnRemarks 駅の名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 50
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String ekiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_densya_eki.delete_flg
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    /**
     * @TableNamem_densya_eki
     * @TableRemarks 電車駅テーブル
     * @ActualColumnName delete_flg
     * @ActualColumnRemarks 削除フラグ
     * @ActualTypeName CHAR
     * @isNullable false
     * @Length 1
     * @Scale 0
     * @DefaultValue 0
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_densya_eki.create_time
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    /**
     * @TableNamem_densya_eki
     * @TableRemarks 電車駅テーブル
     * @ActualColumnName create_time
     * @ActualColumnRemarks 登録日時
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue CURRENT_TIMESTAMP
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_densya_eki.create_user_id
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    /**
     * @TableNamem_densya_eki
     * @TableRemarks 電車駅テーブル
     * @ActualColumnName create_user_id
     * @ActualColumnRemarks 登録者
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_densya_eki.update_time
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    /**
     * @TableNamem_densya_eki
     * @TableRemarks 電車駅テーブル
     * @ActualColumnName update_time
     * @ActualColumnRemarks 更新日時
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue CURRENT_TIMESTAMP
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_densya_eki.update_user_id
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    /**
     * @TableNamem_densya_eki
     * @TableRemarks 電車駅テーブル
     * @ActualColumnName update_user_id
     * @ActualColumnRemarks 更新者
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String updateUserId;
}