package com.baizhi.entity.original;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @author miniw
 * @date 2025/01/18 16:23:43
 * m_densya 電車テーブル
 */
@Accessors(chain = true)
@Data
@Builder
@AllArgsConstructor
public class MDensyaExample implements java.io.Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public MDensyaExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDensyaTypeIsNull() {
            addCriterion("densya_type is null");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeIsNotNull() {
            addCriterion("densya_type is not null");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeEqualTo(String value) {
            addCriterion("densya_type =", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeNotEqualTo(String value) {
            addCriterion("densya_type <>", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeGreaterThan(String value) {
            addCriterion("densya_type >", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeGreaterThanOrEqualTo(String value) {
            addCriterion("densya_type >=", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeLessThan(String value) {
            addCriterion("densya_type <", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeLessThanOrEqualTo(String value) {
            addCriterion("densya_type <=", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeLike(String value) {
            addCriterion("densya_type like", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeNotLike(String value) {
            addCriterion("densya_type not like", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeIn(List<String> values) {
            addCriterion("densya_type in", values, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeNotIn(List<String> values) {
            addCriterion("densya_type not in", values, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeBetween(String value1, String value2) {
            addCriterion("densya_type between", value1, value2, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeNotBetween(String value1, String value2) {
            addCriterion("densya_type not between", value1, value2, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaNoIsNull() {
            addCriterion("densya_no is null");
            return (Criteria) this;
        }

        public Criteria andDensyaNoIsNotNull() {
            addCriterion("densya_no is not null");
            return (Criteria) this;
        }

        public Criteria andDensyaNoEqualTo(Integer value) {
            addCriterion("densya_no =", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoNotEqualTo(Integer value) {
            addCriterion("densya_no <>", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoGreaterThan(Integer value) {
            addCriterion("densya_no >", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("densya_no >=", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoLessThan(Integer value) {
            addCriterion("densya_no <", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoLessThanOrEqualTo(Integer value) {
            addCriterion("densya_no <=", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoIn(List<Integer> values) {
            addCriterion("densya_no in", values, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoNotIn(List<Integer> values) {
            addCriterion("densya_no not in", values, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoBetween(Integer value1, Integer value2) {
            addCriterion("densya_no between", value1, value2, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoNotBetween(Integer value1, Integer value2) {
            addCriterion("densya_no not between", value1, value2, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNameIsNull() {
            addCriterion("densya_name is null");
            return (Criteria) this;
        }

        public Criteria andDensyaNameIsNotNull() {
            addCriterion("densya_name is not null");
            return (Criteria) this;
        }

        public Criteria andDensyaNameEqualTo(String value) {
            addCriterion("densya_name =", value, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameNotEqualTo(String value) {
            addCriterion("densya_name <>", value, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameGreaterThan(String value) {
            addCriterion("densya_name >", value, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameGreaterThanOrEqualTo(String value) {
            addCriterion("densya_name >=", value, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameLessThan(String value) {
            addCriterion("densya_name <", value, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameLessThanOrEqualTo(String value) {
            addCriterion("densya_name <=", value, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameLike(String value) {
            addCriterion("densya_name like", value, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameNotLike(String value) {
            addCriterion("densya_name not like", value, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameIn(List<String> values) {
            addCriterion("densya_name in", values, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameNotIn(List<String> values) {
            addCriterion("densya_name not in", values, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameBetween(String value1, String value2) {
            addCriterion("densya_name between", value1, value2, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDensyaNameNotBetween(String value1, String value2) {
            addCriterion("densya_name not between", value1, value2, "densyaName");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("delete_flg is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("delete_flg is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(String value) {
            addCriterion("delete_flg =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(String value) {
            addCriterion("delete_flg <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(String value) {
            addCriterion("delete_flg >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
            addCriterion("delete_flg >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(String value) {
            addCriterion("delete_flg <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
            addCriterion("delete_flg <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLike(String value) {
            addCriterion("delete_flg like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotLike(String value) {
            addCriterion("delete_flg not like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<String> values) {
            addCriterion("delete_flg in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<String> values) {
            addCriterion("delete_flg not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(String value1, String value2) {
            addCriterion("delete_flg between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(String value1, String value2) {
            addCriterion("delete_flg not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_densya
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 18 16:23:43 JST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}