package com.baizhi.entity.original;

import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @author miniw
 * @date 2025/01/11 15:46:15
 * m_densya 電車テーブル
 */
@Accessors(chain = true)
@Data
public class MDensyaKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_densya.densya_type
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    /**
     * @TableNamem_densya
     * @TableRemarks 電車テーブル
     * @ActualColumnName densya_type
     * @ActualColumnRemarks 電車種別
     * @ActualTypeName CHAR
     * @isNullable false
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String densyaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_densya.densya_no
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    /**
     * @TableNamem_densya
     * @TableRemarks 電車テーブル
     * @ActualColumnName densya_no
     * @ActualColumnRemarks 電車番号
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer densyaNo;
}