package com.baizhi.entity.original;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author user
 * @date 2024/02/08 18:45:15
 * oshi 人の情報
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Oshi implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oshi.id
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    /**
     * @TableNameoshi
     * @TableRemarks 人の情報
     * @ActualColumnName id
     * @ActualColumnRemarks 
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oshi.name
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    /**
     * @TableNameoshi
     * @TableRemarks 人の情報
     * @ActualColumnName name
     * @ActualColumnRemarks 名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 40
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oshi.age
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    /**
     * @TableNameoshi
     * @TableRemarks 人の情報
     * @ActualColumnName age
     * @ActualColumnRemarks 年齢
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 60
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oshi.kamiiro
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    /**
     * @TableNameoshi
     * @TableRemarks 人の情報
     * @ActualColumnName kamiiro
     * @ActualColumnRemarks 髪色
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 40
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String kamiiro;
}