package com.baizhi.entity.original;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @author Lenovo
 * @date 2024/05/19 17:02:35
 * Oucompany 餐饮管理
 */
@Accessors(chain = true)
@Data
@Builder
@AllArgsConstructor
public class OucompanyExample implements java.io.Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public OucompanyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andClientIsNull() {
            addCriterion("client is null");
            return (Criteria) this;
        }

        public Criteria andClientIsNotNull() {
            addCriterion("client is not null");
            return (Criteria) this;
        }

        public Criteria andClientEqualTo(String value) {
            addCriterion("client =", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotEqualTo(String value) {
            addCriterion("client <>", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientGreaterThan(String value) {
            addCriterion("client >", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientGreaterThanOrEqualTo(String value) {
            addCriterion("client >=", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientLessThan(String value) {
            addCriterion("client <", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientLessThanOrEqualTo(String value) {
            addCriterion("client <=", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientLike(String value) {
            addCriterion("client like", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotLike(String value) {
            addCriterion("client not like", value, "client");
            return (Criteria) this;
        }

        public Criteria andClientIn(List<String> values) {
            addCriterion("client in", values, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotIn(List<String> values) {
            addCriterion("client not in", values, "client");
            return (Criteria) this;
        }

        public Criteria andClientBetween(String value1, String value2) {
            addCriterion("client between", value1, value2, "client");
            return (Criteria) this;
        }

        public Criteria andClientNotBetween(String value1, String value2) {
            addCriterion("client not between", value1, value2, "client");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNull() {
            addCriterion("company_type is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNotNull() {
            addCriterion("company_type is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeEqualTo(String value) {
            addCriterion("company_type =", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotEqualTo(String value) {
            addCriterion("company_type <>", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThan(String value) {
            addCriterion("company_type >", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("company_type >=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThan(String value) {
            addCriterion("company_type <", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThanOrEqualTo(String value) {
            addCriterion("company_type <=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLike(String value) {
            addCriterion("company_type like", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotLike(String value) {
            addCriterion("company_type not like", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIn(List<String> values) {
            addCriterion("company_type in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotIn(List<String> values) {
            addCriterion("company_type not in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeBetween(String value1, String value2) {
            addCriterion("company_type between", value1, value2, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotBetween(String value1, String value2) {
            addCriterion("company_type not between", value1, value2, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumIsNull() {
            addCriterion("company_peopleNum is null");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumIsNotNull() {
            addCriterion("company_peopleNum is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumEqualTo(Integer value) {
            addCriterion("company_peopleNum =", value, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumNotEqualTo(Integer value) {
            addCriterion("company_peopleNum <>", value, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumGreaterThan(Integer value) {
            addCriterion("company_peopleNum >", value, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_peopleNum >=", value, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumLessThan(Integer value) {
            addCriterion("company_peopleNum <", value, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumLessThanOrEqualTo(Integer value) {
            addCriterion("company_peopleNum <=", value, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumIn(List<Integer> values) {
            addCriterion("company_peopleNum in", values, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumNotIn(List<Integer> values) {
            addCriterion("company_peopleNum not in", values, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumBetween(Integer value1, Integer value2) {
            addCriterion("company_peopleNum between", value1, value2, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyPeoplenumNotBetween(Integer value1, Integer value2) {
            addCriterion("company_peopleNum not between", value1, value2, "companyPeoplenum");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayIsNull() {
            addCriterion("company_beginDay is null");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayIsNotNull() {
            addCriterion("company_beginDay is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayEqualTo(Date value) {
            addCriterion("company_beginDay =", value, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayNotEqualTo(Date value) {
            addCriterion("company_beginDay <>", value, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayGreaterThan(Date value) {
            addCriterion("company_beginDay >", value, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayGreaterThanOrEqualTo(Date value) {
            addCriterion("company_beginDay >=", value, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayLessThan(Date value) {
            addCriterion("company_beginDay <", value, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayLessThanOrEqualTo(Date value) {
            addCriterion("company_beginDay <=", value, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayIn(List<Date> values) {
            addCriterion("company_beginDay in", values, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayNotIn(List<Date> values) {
            addCriterion("company_beginDay not in", values, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayBetween(Date value1, Date value2) {
            addCriterion("company_beginDay between", value1, value2, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyBegindayNotBetween(Date value1, Date value2) {
            addCriterion("company_beginDay not between", value1, value2, "companyBeginday");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoIsNull() {
            addCriterion("company_photo is null");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoIsNotNull() {
            addCriterion("company_photo is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoEqualTo(String value) {
            addCriterion("company_photo =", value, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoNotEqualTo(String value) {
            addCriterion("company_photo <>", value, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoGreaterThan(String value) {
            addCriterion("company_photo >", value, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("company_photo >=", value, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoLessThan(String value) {
            addCriterion("company_photo <", value, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoLessThanOrEqualTo(String value) {
            addCriterion("company_photo <=", value, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoLike(String value) {
            addCriterion("company_photo like", value, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoNotLike(String value) {
            addCriterion("company_photo not like", value, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoIn(List<String> values) {
            addCriterion("company_photo in", values, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoNotIn(List<String> values) {
            addCriterion("company_photo not in", values, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoBetween(String value1, String value2) {
            addCriterion("company_photo between", value1, value2, "companyPhoto");
            return (Criteria) this;
        }

        public Criteria andCompanyPhotoNotBetween(String value1, String value2) {
            addCriterion("company_photo not between", value1, value2, "companyPhoto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Oucompany
     *
     * @mbg.generated do_not_delete_during_merge Sun May 19 17:02:36 JST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}