package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author Lenovo
 * @date 2024/05/19 17:02:35
 * Oucompany 餐饮管理
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Oucompany implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Oucompany.id
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    /**
     * @TableNameOucompany
     * @TableRemarks 餐饮管理
     * @ActualColumnName id
     * @ActualColumnRemarks NO
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Oucompany.client
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    /**
     * @TableNameOucompany
     * @TableRemarks 餐饮管理
     * @ActualColumnName client
     * @ActualColumnRemarks 企业会员
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 10000
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String client;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Oucompany.company_type
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    /**
     * @TableNameOucompany
     * @TableRemarks 餐饮管理
     * @ActualColumnName company_type
     * @ActualColumnRemarks 公司性质　0:有限公司　1:个人经营
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String companyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Oucompany.company_peopleNum
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    /**
     * @TableNameOucompany
     * @TableRemarks 餐饮管理
     * @ActualColumnName company_peopleNum
     * @ActualColumnRemarks 公司员工
     * @ActualTypeName INT
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer companyPeoplenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Oucompany.company_beginDay
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    /**
     * @TableNameOucompany
     * @TableRemarks 餐饮管理
     * @ActualColumnName company_beginDay
     * @ActualColumnRemarks 公司入会注册时间
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date companyBeginday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Oucompany.company_photo
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    /**
     * @TableNameOucompany
     * @TableRemarks 餐饮管理
     * @ActualColumnName company_photo
     * @ActualColumnRemarks 公司样貌
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 200
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String companyPhoto;
}