package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author tech
 * @date 2023/11/19 11:14:01
 * salesrecords 销售记录
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Salesrecords implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesrecords.id
     *
     * @mbg.generated Sun Nov 19 11:14:02 JST 2023
     */
    /**
     * @TableNamesalesrecords
     * @TableRemarks 销售记录
     * @ActualColumnName id
     * @ActualColumnRemarks 
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesrecords.product_name
     *
     * @mbg.generated Sun Nov 19 11:14:02 JST 2023
     */
    /**
     * @TableNamesalesrecords
     * @TableRemarks 销售记录
     * @ActualColumnName product_name
     * @ActualColumnRemarks 商品名
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 40
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesrecords.price
     *
     * @mbg.generated Sun Nov 19 11:14:02 JST 2023
     */
    /**
     * @TableNamesalesrecords
     * @TableRemarks 销售记录
     * @ActualColumnName price
     * @ActualColumnRemarks 价格
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 60
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesrecords.sales_date
     *
     * @mbg.generated Sun Nov 19 11:14:02 JST 2023
     */
    /**
     * @TableNamesalesrecords
     * @TableRemarks 销售记录
     * @ActualColumnName sales_date
     * @ActualColumnRemarks 售出日期
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date salesDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesrecords.picture
     *
     * @mbg.generated Sun Nov 19 11:14:02 JST 2023
     */
    /**
     * @TableNamesalesrecords
     * @TableRemarks 销售记录
     * @ActualColumnName picture
     * @ActualColumnRemarks 图片路径
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 200
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String picture;
}