package com.baizhi.entity.original;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author miniw
 * @date 2025/01/11 15:46:15
 * senmongakusei 専門学生テーブル
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Senmongakusei implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senmongakusei.student_id
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    /**
     * @TableNamesenmongakusei
     * @TableRemarks 専門学生テーブル
     * @ActualColumnName student_id
     * @ActualColumnRemarks ID
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senmongakusei.student_name
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    /**
     * @TableNamesenmongakusei
     * @TableRemarks 専門学生テーブル
     * @ActualColumnName student_name
     * @ActualColumnRemarks 名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 50
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senmongakusei.sex
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    /**
     * @TableNamesenmongakusei
     * @TableRemarks 専門学生テーブル
     * @ActualColumnName sex
     * @ActualColumnRemarks 性別
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senmongakusei.gakka
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    /**
     * @TableNamesenmongakusei
     * @TableRemarks 専門学生テーブル
     * @ActualColumnName gakka
     * @ActualColumnRemarks 学科
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String gakka;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senmongakusei.course
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    /**
     * @TableNamesenmongakusei
     * @TableRemarks 専門学生テーブル
     * @ActualColumnName course
     * @ActualColumnRemarks コース
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column senmongakusei.mail
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    /**
     * @TableNamesenmongakusei
     * @TableRemarks 専門学生テーブル
     * @ActualColumnName mail
     * @ActualColumnRemarks メールアドレス
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 200
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String mail;
}