package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author user
 * @date 2024/02/08 18:45:15
 * snacks おやつ
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Snacks implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks.id
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    /**
     * @TableNamesnacks
     * @TableRemarks おやつ
     * @ActualColumnName id
     * @ActualColumnRemarks 
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks.name
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    /**
     * @TableNamesnacks
     * @TableRemarks おやつ
     * @ActualColumnName name
     * @ActualColumnRemarks 商品名称
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 60
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks.salary
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    /**
     * @TableNamesnacks
     * @TableRemarks おやつ
     * @ActualColumnName salary
     * @ActualColumnRemarks 商品价格
     * @ActualTypeName DOUBLE
     * @isNullable true
     * @Length 10
     * @Scale 2
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName DOUBLE
     * @JdbcType 8
     */
    private Double salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks.pof
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    /**
     * @TableNamesnacks
     * @TableRemarks おやつ
     * @ActualColumnName pof
     * @ActualColumnRemarks 赏味期限
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date pof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks.photo
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    /**
     * @TableNamesnacks
     * @TableRemarks おやつ
     * @ActualColumnName photo
     * @ActualColumnRemarks 商品图片
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 200
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String photo;
}