package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author admin
 * @date 2024/11/25 11:31:52
 * t_buken 賃貸不動産テーブル
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TBuken implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.buken_id
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName buken_id
     * @ActualColumnRemarks NO
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity true
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer bukenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.location
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName location
     * @ActualColumnRemarks 所在地
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 100
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.near_station_time
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName near_station_time
     * @ActualColumnRemarks 最寄り駅まで徒歩何分
     * @ActualTypeName INT UNSIGNED
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer nearStationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.buken_year
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName buken_year
     * @ActualColumnRemarks 築年数
     * @ActualTypeName INT UNSIGNED
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer bukenYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.madori
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName madori
     * @ActualColumnRemarks 間取り
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String madori;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.area
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName area
     * @ActualColumnRemarks 面積
     * @ActualTypeName INT UNSIGNED
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.direction
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName direction
     * @ActualColumnRemarks 向き
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.buken_condition
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName buken_condition
     * @ActualColumnRemarks 限定条件
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 100
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String bukenCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.money_rent
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName money_rent
     * @ActualColumnRemarks 賃料
     * @ActualTypeName INT UNSIGNED
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer moneyRent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.money_deposit
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName money_deposit
     * @ActualColumnRemarks 敷金
     * @ActualTypeName INT UNSIGNED
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer moneyDeposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.money_gift
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName money_gift
     * @ActualColumnRemarks 礼金
     * @ActualTypeName INT UNSIGNED
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer moneyGift;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.money_management
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName money_management
     * @ActualColumnRemarks 管理費/共益費
     * @ActualTypeName INT UNSIGNED
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer moneyManagement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.buken_type
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName buken_type
     * @ActualColumnRemarks 建物種別
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String bukenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.device
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName device
     * @ActualColumnRemarks 設備
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 100
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String device;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.delete_flg
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName delete_flg
     * @ActualColumnRemarks 削除フラグ
     * @ActualTypeName CHAR
     * @isNullable false
     * @Length 1
     * @Scale 0
     * @DefaultValue 0
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.create_time
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName create_time
     * @ActualColumnRemarks 登録日時
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue CURRENT_TIMESTAMP
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.create_user_id
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName create_user_id
     * @ActualColumnRemarks 登録者
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.update_time
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName update_time
     * @ActualColumnRemarks 更新日時
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue CURRENT_TIMESTAMP
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken.update_user_id
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken
     * @TableRemarks 賃貸不動産テーブル
     * @ActualColumnName update_user_id
     * @ActualColumnRemarks 更新者
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String updateUserId;
}