package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author admin
 * @date 2024/11/25 11:31:52
 * t_buken_icon 物件アイコンテーブル
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TBukenIcon extends TBukenIconKey implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken_icon.url
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken_icon
     * @TableRemarks 物件アイコンテーブル
     * @ActualColumnName url
     * @ActualColumnRemarks アイコン
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 1000
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken_icon.delete_flg
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken_icon
     * @TableRemarks 物件アイコンテーブル
     * @ActualColumnName delete_flg
     * @ActualColumnRemarks 削除フラグ
     * @ActualTypeName CHAR
     * @isNullable false
     * @Length 1
     * @Scale 0
     * @DefaultValue 0
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken_icon.create_time
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken_icon
     * @TableRemarks 物件アイコンテーブル
     * @ActualColumnName create_time
     * @ActualColumnRemarks 登録日時
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue CURRENT_TIMESTAMP
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken_icon.create_user_id
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken_icon
     * @TableRemarks 物件アイコンテーブル
     * @ActualColumnName create_user_id
     * @ActualColumnRemarks 登録者
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken_icon.update_time
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken_icon
     * @TableRemarks 物件アイコンテーブル
     * @ActualColumnName update_time
     * @ActualColumnRemarks 更新日時
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue CURRENT_TIMESTAMP
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken_icon.update_user_id
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_buken_icon
     * @TableRemarks 物件アイコンテーブル
     * @ActualColumnName update_user_id
     * @ActualColumnRemarks 更新者
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 20
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String updateUserId;
}