package com.baizhi.entity.original;

import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @author miniw
 * @date 2025/01/18 16:23:43
 * t_buken_icon 物件アイコンテーブル
 */
@Accessors(chain = true)
@Data
public class TBukenIconKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken_icon.buken_id
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    /**
     * @TableNamet_buken_icon
     * @TableRemarks 物件アイコンテーブル
     * @ActualColumnName buken_id
     * @ActualColumnRemarks 物件番号
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer bukenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buken_icon.sub_id
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    /**
     * @TableNamet_buken_icon
     * @TableRemarks 物件アイコンテーブル
     * @ActualColumnName sub_id
     * @ActualColumnRemarks 枝番
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer subId;
}