package com.baizhi.entity.original;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @author miniw
 * @date 2025/01/18 16:23:43
 * t_buken 賃貸不動産テーブル
 */
@Accessors(chain = true)
@Data
@Builder
@AllArgsConstructor
public class TBukenExample implements java.io.Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public TBukenExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBukenIdIsNull() {
            addCriterion("buken_id is null");
            return (Criteria) this;
        }

        public Criteria andBukenIdIsNotNull() {
            addCriterion("buken_id is not null");
            return (Criteria) this;
        }

        public Criteria andBukenIdEqualTo(Integer value) {
            addCriterion("buken_id =", value, "bukenId");
            return (Criteria) this;
        }

        public Criteria andBukenIdNotEqualTo(Integer value) {
            addCriterion("buken_id <>", value, "bukenId");
            return (Criteria) this;
        }

        public Criteria andBukenIdGreaterThan(Integer value) {
            addCriterion("buken_id >", value, "bukenId");
            return (Criteria) this;
        }

        public Criteria andBukenIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("buken_id >=", value, "bukenId");
            return (Criteria) this;
        }

        public Criteria andBukenIdLessThan(Integer value) {
            addCriterion("buken_id <", value, "bukenId");
            return (Criteria) this;
        }

        public Criteria andBukenIdLessThanOrEqualTo(Integer value) {
            addCriterion("buken_id <=", value, "bukenId");
            return (Criteria) this;
        }

        public Criteria andBukenIdIn(List<Integer> values) {
            addCriterion("buken_id in", values, "bukenId");
            return (Criteria) this;
        }

        public Criteria andBukenIdNotIn(List<Integer> values) {
            addCriterion("buken_id not in", values, "bukenId");
            return (Criteria) this;
        }

        public Criteria andBukenIdBetween(Integer value1, Integer value2) {
            addCriterion("buken_id between", value1, value2, "bukenId");
            return (Criteria) this;
        }

        public Criteria andBukenIdNotBetween(Integer value1, Integer value2) {
            addCriterion("buken_id not between", value1, value2, "bukenId");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeIsNull() {
            addCriterion("densya_type is null");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeIsNotNull() {
            addCriterion("densya_type is not null");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeEqualTo(String value) {
            addCriterion("densya_type =", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeNotEqualTo(String value) {
            addCriterion("densya_type <>", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeGreaterThan(String value) {
            addCriterion("densya_type >", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeGreaterThanOrEqualTo(String value) {
            addCriterion("densya_type >=", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeLessThan(String value) {
            addCriterion("densya_type <", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeLessThanOrEqualTo(String value) {
            addCriterion("densya_type <=", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeLike(String value) {
            addCriterion("densya_type like", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeNotLike(String value) {
            addCriterion("densya_type not like", value, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeIn(List<String> values) {
            addCriterion("densya_type in", values, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeNotIn(List<String> values) {
            addCriterion("densya_type not in", values, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeBetween(String value1, String value2) {
            addCriterion("densya_type between", value1, value2, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaTypeNotBetween(String value1, String value2) {
            addCriterion("densya_type not between", value1, value2, "densyaType");
            return (Criteria) this;
        }

        public Criteria andDensyaNoIsNull() {
            addCriterion("densya_no is null");
            return (Criteria) this;
        }

        public Criteria andDensyaNoIsNotNull() {
            addCriterion("densya_no is not null");
            return (Criteria) this;
        }

        public Criteria andDensyaNoEqualTo(Integer value) {
            addCriterion("densya_no =", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoNotEqualTo(Integer value) {
            addCriterion("densya_no <>", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoGreaterThan(Integer value) {
            addCriterion("densya_no >", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("densya_no >=", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoLessThan(Integer value) {
            addCriterion("densya_no <", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoLessThanOrEqualTo(Integer value) {
            addCriterion("densya_no <=", value, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoIn(List<Integer> values) {
            addCriterion("densya_no in", values, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoNotIn(List<Integer> values) {
            addCriterion("densya_no not in", values, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoBetween(Integer value1, Integer value2) {
            addCriterion("densya_no between", value1, value2, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andDensyaNoNotBetween(Integer value1, Integer value2) {
            addCriterion("densya_no not between", value1, value2, "densyaNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoIsNull() {
            addCriterion("eki_no is null");
            return (Criteria) this;
        }

        public Criteria andEkiNoIsNotNull() {
            addCriterion("eki_no is not null");
            return (Criteria) this;
        }

        public Criteria andEkiNoEqualTo(Integer value) {
            addCriterion("eki_no =", value, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoNotEqualTo(Integer value) {
            addCriterion("eki_no <>", value, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoGreaterThan(Integer value) {
            addCriterion("eki_no >", value, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("eki_no >=", value, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoLessThan(Integer value) {
            addCriterion("eki_no <", value, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoLessThanOrEqualTo(Integer value) {
            addCriterion("eki_no <=", value, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoIn(List<Integer> values) {
            addCriterion("eki_no in", values, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoNotIn(List<Integer> values) {
            addCriterion("eki_no not in", values, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoBetween(Integer value1, Integer value2) {
            addCriterion("eki_no between", value1, value2, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andEkiNoNotBetween(Integer value1, Integer value2) {
            addCriterion("eki_no not between", value1, value2, "ekiNo");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeIsNull() {
            addCriterion("near_station_time is null");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeIsNotNull() {
            addCriterion("near_station_time is not null");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeEqualTo(Integer value) {
            addCriterion("near_station_time =", value, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeNotEqualTo(Integer value) {
            addCriterion("near_station_time <>", value, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeGreaterThan(Integer value) {
            addCriterion("near_station_time >", value, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("near_station_time >=", value, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeLessThan(Integer value) {
            addCriterion("near_station_time <", value, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeLessThanOrEqualTo(Integer value) {
            addCriterion("near_station_time <=", value, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeIn(List<Integer> values) {
            addCriterion("near_station_time in", values, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeNotIn(List<Integer> values) {
            addCriterion("near_station_time not in", values, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeBetween(Integer value1, Integer value2) {
            addCriterion("near_station_time between", value1, value2, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andNearStationTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("near_station_time not between", value1, value2, "nearStationTime");
            return (Criteria) this;
        }

        public Criteria andBukenYearIsNull() {
            addCriterion("buken_year is null");
            return (Criteria) this;
        }

        public Criteria andBukenYearIsNotNull() {
            addCriterion("buken_year is not null");
            return (Criteria) this;
        }

        public Criteria andBukenYearEqualTo(Integer value) {
            addCriterion("buken_year =", value, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andBukenYearNotEqualTo(Integer value) {
            addCriterion("buken_year <>", value, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andBukenYearGreaterThan(Integer value) {
            addCriterion("buken_year >", value, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andBukenYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("buken_year >=", value, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andBukenYearLessThan(Integer value) {
            addCriterion("buken_year <", value, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andBukenYearLessThanOrEqualTo(Integer value) {
            addCriterion("buken_year <=", value, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andBukenYearIn(List<Integer> values) {
            addCriterion("buken_year in", values, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andBukenYearNotIn(List<Integer> values) {
            addCriterion("buken_year not in", values, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andBukenYearBetween(Integer value1, Integer value2) {
            addCriterion("buken_year between", value1, value2, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andBukenYearNotBetween(Integer value1, Integer value2) {
            addCriterion("buken_year not between", value1, value2, "bukenYear");
            return (Criteria) this;
        }

        public Criteria andMadoriIsNull() {
            addCriterion("madori is null");
            return (Criteria) this;
        }

        public Criteria andMadoriIsNotNull() {
            addCriterion("madori is not null");
            return (Criteria) this;
        }

        public Criteria andMadoriEqualTo(String value) {
            addCriterion("madori =", value, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriNotEqualTo(String value) {
            addCriterion("madori <>", value, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriGreaterThan(String value) {
            addCriterion("madori >", value, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriGreaterThanOrEqualTo(String value) {
            addCriterion("madori >=", value, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriLessThan(String value) {
            addCriterion("madori <", value, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriLessThanOrEqualTo(String value) {
            addCriterion("madori <=", value, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriLike(String value) {
            addCriterion("madori like", value, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriNotLike(String value) {
            addCriterion("madori not like", value, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriIn(List<String> values) {
            addCriterion("madori in", values, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriNotIn(List<String> values) {
            addCriterion("madori not in", values, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriBetween(String value1, String value2) {
            addCriterion("madori between", value1, value2, "madori");
            return (Criteria) this;
        }

        public Criteria andMadoriNotBetween(String value1, String value2) {
            addCriterion("madori not between", value1, value2, "madori");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(Integer value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(Integer value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(Integer value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(Integer value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(Integer value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(Integer value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<Integer> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<Integer> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(Integer value1, Integer value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(Integer value1, Integer value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("direction is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("direction is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(String value) {
            addCriterion("direction =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(String value) {
            addCriterion("direction <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(String value) {
            addCriterion("direction >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("direction >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(String value) {
            addCriterion("direction <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(String value) {
            addCriterion("direction <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLike(String value) {
            addCriterion("direction like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotLike(String value) {
            addCriterion("direction not like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<String> values) {
            addCriterion("direction in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<String> values) {
            addCriterion("direction not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(String value1, String value2) {
            addCriterion("direction between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(String value1, String value2) {
            addCriterion("direction not between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andBukenConditionIsNull() {
            addCriterion("buken_condition is null");
            return (Criteria) this;
        }

        public Criteria andBukenConditionIsNotNull() {
            addCriterion("buken_condition is not null");
            return (Criteria) this;
        }

        public Criteria andBukenConditionEqualTo(String value) {
            addCriterion("buken_condition =", value, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionNotEqualTo(String value) {
            addCriterion("buken_condition <>", value, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionGreaterThan(String value) {
            addCriterion("buken_condition >", value, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionGreaterThanOrEqualTo(String value) {
            addCriterion("buken_condition >=", value, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionLessThan(String value) {
            addCriterion("buken_condition <", value, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionLessThanOrEqualTo(String value) {
            addCriterion("buken_condition <=", value, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionLike(String value) {
            addCriterion("buken_condition like", value, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionNotLike(String value) {
            addCriterion("buken_condition not like", value, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionIn(List<String> values) {
            addCriterion("buken_condition in", values, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionNotIn(List<String> values) {
            addCriterion("buken_condition not in", values, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionBetween(String value1, String value2) {
            addCriterion("buken_condition between", value1, value2, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andBukenConditionNotBetween(String value1, String value2) {
            addCriterion("buken_condition not between", value1, value2, "bukenCondition");
            return (Criteria) this;
        }

        public Criteria andMoneyRentIsNull() {
            addCriterion("money_rent is null");
            return (Criteria) this;
        }

        public Criteria andMoneyRentIsNotNull() {
            addCriterion("money_rent is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyRentEqualTo(Integer value) {
            addCriterion("money_rent =", value, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyRentNotEqualTo(Integer value) {
            addCriterion("money_rent <>", value, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyRentGreaterThan(Integer value) {
            addCriterion("money_rent >", value, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyRentGreaterThanOrEqualTo(Integer value) {
            addCriterion("money_rent >=", value, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyRentLessThan(Integer value) {
            addCriterion("money_rent <", value, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyRentLessThanOrEqualTo(Integer value) {
            addCriterion("money_rent <=", value, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyRentIn(List<Integer> values) {
            addCriterion("money_rent in", values, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyRentNotIn(List<Integer> values) {
            addCriterion("money_rent not in", values, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyRentBetween(Integer value1, Integer value2) {
            addCriterion("money_rent between", value1, value2, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyRentNotBetween(Integer value1, Integer value2) {
            addCriterion("money_rent not between", value1, value2, "moneyRent");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositIsNull() {
            addCriterion("money_deposit is null");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositIsNotNull() {
            addCriterion("money_deposit is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositEqualTo(Integer value) {
            addCriterion("money_deposit =", value, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositNotEqualTo(Integer value) {
            addCriterion("money_deposit <>", value, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositGreaterThan(Integer value) {
            addCriterion("money_deposit >", value, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositGreaterThanOrEqualTo(Integer value) {
            addCriterion("money_deposit >=", value, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositLessThan(Integer value) {
            addCriterion("money_deposit <", value, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositLessThanOrEqualTo(Integer value) {
            addCriterion("money_deposit <=", value, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositIn(List<Integer> values) {
            addCriterion("money_deposit in", values, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositNotIn(List<Integer> values) {
            addCriterion("money_deposit not in", values, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositBetween(Integer value1, Integer value2) {
            addCriterion("money_deposit between", value1, value2, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyDepositNotBetween(Integer value1, Integer value2) {
            addCriterion("money_deposit not between", value1, value2, "moneyDeposit");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftIsNull() {
            addCriterion("money_gift is null");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftIsNotNull() {
            addCriterion("money_gift is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftEqualTo(Integer value) {
            addCriterion("money_gift =", value, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftNotEqualTo(Integer value) {
            addCriterion("money_gift <>", value, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftGreaterThan(Integer value) {
            addCriterion("money_gift >", value, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftGreaterThanOrEqualTo(Integer value) {
            addCriterion("money_gift >=", value, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftLessThan(Integer value) {
            addCriterion("money_gift <", value, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftLessThanOrEqualTo(Integer value) {
            addCriterion("money_gift <=", value, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftIn(List<Integer> values) {
            addCriterion("money_gift in", values, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftNotIn(List<Integer> values) {
            addCriterion("money_gift not in", values, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftBetween(Integer value1, Integer value2) {
            addCriterion("money_gift between", value1, value2, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyGiftNotBetween(Integer value1, Integer value2) {
            addCriterion("money_gift not between", value1, value2, "moneyGift");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementIsNull() {
            addCriterion("money_management is null");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementIsNotNull() {
            addCriterion("money_management is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementEqualTo(Integer value) {
            addCriterion("money_management =", value, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementNotEqualTo(Integer value) {
            addCriterion("money_management <>", value, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementGreaterThan(Integer value) {
            addCriterion("money_management >", value, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementGreaterThanOrEqualTo(Integer value) {
            addCriterion("money_management >=", value, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementLessThan(Integer value) {
            addCriterion("money_management <", value, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementLessThanOrEqualTo(Integer value) {
            addCriterion("money_management <=", value, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementIn(List<Integer> values) {
            addCriterion("money_management in", values, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementNotIn(List<Integer> values) {
            addCriterion("money_management not in", values, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementBetween(Integer value1, Integer value2) {
            addCriterion("money_management between", value1, value2, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andMoneyManagementNotBetween(Integer value1, Integer value2) {
            addCriterion("money_management not between", value1, value2, "moneyManagement");
            return (Criteria) this;
        }

        public Criteria andBukenTypeIsNull() {
            addCriterion("buken_type is null");
            return (Criteria) this;
        }

        public Criteria andBukenTypeIsNotNull() {
            addCriterion("buken_type is not null");
            return (Criteria) this;
        }

        public Criteria andBukenTypeEqualTo(String value) {
            addCriterion("buken_type =", value, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeNotEqualTo(String value) {
            addCriterion("buken_type <>", value, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeGreaterThan(String value) {
            addCriterion("buken_type >", value, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeGreaterThanOrEqualTo(String value) {
            addCriterion("buken_type >=", value, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeLessThan(String value) {
            addCriterion("buken_type <", value, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeLessThanOrEqualTo(String value) {
            addCriterion("buken_type <=", value, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeLike(String value) {
            addCriterion("buken_type like", value, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeNotLike(String value) {
            addCriterion("buken_type not like", value, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeIn(List<String> values) {
            addCriterion("buken_type in", values, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeNotIn(List<String> values) {
            addCriterion("buken_type not in", values, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeBetween(String value1, String value2) {
            addCriterion("buken_type between", value1, value2, "bukenType");
            return (Criteria) this;
        }

        public Criteria andBukenTypeNotBetween(String value1, String value2) {
            addCriterion("buken_type not between", value1, value2, "bukenType");
            return (Criteria) this;
        }

        public Criteria andDeviceIsNull() {
            addCriterion("device is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIsNotNull() {
            addCriterion("device is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceEqualTo(String value) {
            addCriterion("device =", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotEqualTo(String value) {
            addCriterion("device <>", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceGreaterThan(String value) {
            addCriterion("device >", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceGreaterThanOrEqualTo(String value) {
            addCriterion("device >=", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceLessThan(String value) {
            addCriterion("device <", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceLessThanOrEqualTo(String value) {
            addCriterion("device <=", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceLike(String value) {
            addCriterion("device like", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotLike(String value) {
            addCriterion("device not like", value, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceIn(List<String> values) {
            addCriterion("device in", values, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotIn(List<String> values) {
            addCriterion("device not in", values, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceBetween(String value1, String value2) {
            addCriterion("device between", value1, value2, "device");
            return (Criteria) this;
        }

        public Criteria andDeviceNotBetween(String value1, String value2) {
            addCriterion("device not between", value1, value2, "device");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("delete_flg is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("delete_flg is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(String value) {
            addCriterion("delete_flg =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(String value) {
            addCriterion("delete_flg <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(String value) {
            addCriterion("delete_flg >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
            addCriterion("delete_flg >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(String value) {
            addCriterion("delete_flg <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
            addCriterion("delete_flg <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLike(String value) {
            addCriterion("delete_flg like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotLike(String value) {
            addCriterion("delete_flg not like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<String> values) {
            addCriterion("delete_flg in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<String> values) {
            addCriterion("delete_flg not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(String value1, String value2) {
            addCriterion("delete_flg between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(String value1, String value2) {
            addCriterion("delete_flg not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_buken
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 18 16:23:43 JST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_buken
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}