package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author admin
 * @date 2024/11/25 11:31:52
 * t_company 会社テーブル
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TCompany implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.id
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_company
     * @TableRemarks 会社テーブル
     * @ActualColumnName id
     * @ActualColumnRemarks id
     * @ActualTypeName INT
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.name
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_company
     * @TableRemarks 会社テーブル
     * @ActualColumnName name
     * @ActualColumnRemarks 名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 255
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.type
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_company
     * @TableRemarks 会社テーブル
     * @ActualColumnName type
     * @ActualColumnRemarks 1:合同会社2:株式会社
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 1
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.create_date
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_company
     * @TableRemarks 会社テーブル
     * @ActualColumnName create_date
     * @ActualColumnRemarks 創立日
     * @ActualTypeName DATE
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn true
     * @isJDBCTimeColumn false
     * @JdbcTypeName DATE
     * @JdbcType 91
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_company.icon
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    /**
     * @TableNamet_company
     * @TableRemarks 会社テーブル
     * @ActualColumnName icon
     * @ActualColumnRemarks 画像
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 1000
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String icon;
}