package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author li117
 * @date 2024/05/12 17:21:01
 * fruit 水果
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TFruit implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.id
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    /**
     * @TableNamefruit
     * @TableRemarks 水果
     * @ActualColumnName id
     * @ActualColumnRemarks NO
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.name
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    /**
     * @TableNamefruit
     * @TableRemarks 水果
     * @ActualColumnName name
     * @ActualColumnRemarks 名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 60
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.price
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    /**
     * @TableNamefruit
     * @TableRemarks 水果
     * @ActualColumnName price
     * @ActualColumnRemarks 价格
     * @ActualTypeName DOUBLE
     * @isNullable true
     * @Length 10
     * @Scale 2
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName DOUBLE
     * @JdbcType 8
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.production
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    /**
     * @TableNamefruit
     * @TableRemarks 水果
     * @ActualColumnName production
     * @ActualColumnRemarks 生产年月日
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date production;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.photo
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    /**
     * @TableNamefruit
     * @TableRemarks 水果
     * @ActualColumnName photo
     * @ActualColumnRemarks 图片
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 200
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.color
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    /**
     * @TableNamefruit
     * @TableRemarks 水果
     * @ActualColumnName color
     * @ActualColumnRemarks 颜色
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.foreign_type
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    /**
     * @TableNamefruit
     * @TableRemarks 水果
     * @ActualColumnName foreign_type
     * @ActualColumnRemarks 外語
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 255
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String foreignType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.country_of_origin
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    /**
     * @TableNamefruit
     * @TableRemarks 水果
     * @ActualColumnName country_of_origin
     * @ActualColumnRemarks 出产国
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String countryOfOrigin;
}