package com.baizhi.entity.original;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author jianb
 * @date 2024/03/24 12:48:14
 * hakoneekidenranking 
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class THakoneEkidenRanking implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hakoneekidenranking.id
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    /**
     * @TableNamehakoneekidenranking
     * @TableRemarks 
     * @ActualColumnName id
     * @ActualColumnRemarks 
     * @ActualTypeName INT
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hakoneekidenranking.position
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    /**
     * @TableNamehakoneekidenranking
     * @TableRemarks 
     * @ActualColumnName position
     * @ActualColumnRemarks 
     * @ActualTypeName INT
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hakoneekidenranking.team_name
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    /**
     * @TableNamehakoneekidenranking
     * @TableRemarks 
     * @ActualColumnName team_name
     * @ActualColumnRemarks 
     * @ActualTypeName VARCHAR
     * @isNullable false
     * @Length 255
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hakoneekidenranking.record
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    /**
     * @TableNamehakoneekidenranking
     * @TableRemarks 
     * @ActualColumnName record
     * @ActualColumnRemarks 
     * @ActualTypeName TIME
     * @isNullable false
     * @Length 8
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn true
     * @JdbcTypeName TIME
     * @JdbcType 92
     */
    private Date record;
    private String photo;
}