package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author user
 * @date 2024/05/12 14:45:26
 * house 賃貸住宅
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Thouse implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.id
     *
     * @mbg.generated Sun May 12 14:45:27 JST 2024
     */
    /**
     * @TableNamehouse
     * @TableRemarks 賃貸住宅
     * @ActualColumnName id
     * @ActualColumnRemarks NO
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.name
     *
     * @mbg.generated Sun May 12 14:45:27 JST 2024
     */
    /**
     * @TableNamehouse
     * @TableRemarks 賃貸住宅
     * @ActualColumnName name
     * @ActualColumnRemarks 名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 60
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.rent_fee
     *
     * @mbg.generated Sun May 12 14:45:27 JST 2024
     */
    /**
     * @TableNamehouse
     * @TableRemarks 賃貸住宅
     * @ActualColumnName rent_fee
     * @ActualColumnRemarks 賃料
     * @ActualTypeName DOUBLE
     * @isNullable true
     * @Length 5
     * @Scale 2
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName DOUBLE
     * @JdbcType 8
     */
    private Double rentFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.house_billd
     *
     * @mbg.generated Sun May 12 14:45:27 JST 2024
     */
    /**
     * @TableNamehouse
     * @TableRemarks 賃貸住宅
     * @ActualColumnName house_billd
     * @ActualColumnRemarks 定礎年月日
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date houseBilld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.photo
     *
     * @mbg.generated Sun May 12 14:45:27 JST 2024
     */
    /**
     * @TableNamehouse
     * @TableRemarks 賃貸住宅
     * @ActualColumnName photo
     * @ActualColumnRemarks 室内写真
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 200
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.grade
     *
     * @mbg.generated Sun May 12 14:45:27 JST 2024
     */
    /**
     * @TableNamehouse
     * @TableRemarks 賃貸住宅
     * @ActualColumnName grade
     * @ActualColumnRemarks グレード
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.addres
     *
     * @mbg.generated Sun May 12 14:45:27 JST 2024
     */
    /**
     * @TableNamehouse
     * @TableRemarks 賃貸住宅
     * @ActualColumnName addres
     * @ActualColumnRemarks 住所
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 255
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String addres;
}