package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author INDEX
 * @date 2024/06/30 17:08:01
 * Mymessage CUIBOHUA
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TMymessage implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Mymessage.id
     *
     * @mbg.generated Sun Jun 30 17:08:01 JST 2024
     */
    /**
     * @TableNameMymessage
     * @TableRemarks CUIBOHUA
     * @ActualColumnName id
     * @ActualColumnRemarks NO
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Mymessage.name
     *
     * @mbg.generated Sun Jun 30 17:08:01 JST 2024
     */
    /**
     * @TableNameMymessage
     * @TableRemarks CUIBOHUA
     * @ActualColumnName name
     * @ActualColumnRemarks my name
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 60
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Mymessage.jikan
     *
     * @mbg.generated Sun Jun 30 17:08:01 JST 2024
     */
    /**
     * @TableNameMymessage
     * @TableRemarks CUIBOHUA
     * @ActualColumnName jikan
     * @ActualColumnRemarks jikan
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date jikan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Mymessage.age
     *
     * @mbg.generated Sun Jun 30 17:08:01 JST 2024
     */
    /**
     * @TableNameMymessage
     * @TableRemarks CUIBOHUA
     * @ActualColumnName age
     * @ActualColumnRemarks age
     * @ActualTypeName INT
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer age;
}