package com.baizhi.entity.original;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author 24989
 * @date 2024/05/12 13:58:15
 * TokyoMetro1 メトロ表
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TokyoMetro1 implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TokyoMetro1.id
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    /**
     * @TableNameTokyoMetro1
     * @TableRemarks メトロ表
     * @ActualColumnName id
     * @ActualColumnRemarks 東京メトロ
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TokyoMetro1.metroname
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    /**
     * @TableNameTokyoMetro1
     * @TableRemarks メトロ表
     * @ActualColumnName metroname
     * @ActualColumnRemarks 名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 50
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String metroname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TokyoMetro1.timetable
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    /**
     * @TableNameTokyoMetro1
     * @TableRemarks メトロ表
     * @ActualColumnName timetable
     * @ActualColumnRemarks 時刻表
     * @ActualTypeName DOUBLE
     * @isNullable true
     * @Length 10
     * @Scale 2
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName DOUBLE
     * @JdbcType 8
     */
    private Double timetable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TokyoMetro1.fare
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    /**
     * @TableNameTokyoMetro1
     * @TableRemarks メトロ表
     * @ActualColumnName fare
     * @ActualColumnRemarks 運賃
     * @ActualTypeName DOUBLE
     * @isNullable true
     * @Length 10
     * @Scale 2
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName DOUBLE
     * @JdbcType 8
     */
    private Double fare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TokyoMetro1.photo
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    /**
     * @TableNameTokyoMetro1
     * @TableRemarks メトロ表
     * @ActualColumnName photo
     * @ActualColumnRemarks アイコン
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 200
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TokyoMetro1.station
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    /**
     * @TableNameTokyoMetro1
     * @TableRemarks メトロ表
     * @ActualColumnName station
     * @ActualColumnRemarks 駅
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 255
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String station;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TokyoMetro1.transfer
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    /**
     * @TableNameTokyoMetro1
     * @TableRemarks メトロ表
     * @ActualColumnName transfer
     * @ActualColumnRemarks 乗換
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 240
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String transfer;
}