package com.baizhi.entity.original;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @author user
 * @date 2024/05/27 17:56:13
 * rentlist 
 */
@Accessors(chain = true)
@Data
@Builder
@AllArgsConstructor
public class TrentExample implements java.io.Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public TrentExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHouseidIsNull() {
            addCriterion("houseid is null");
            return (Criteria) this;
        }

        public Criteria andHouseidIsNotNull() {
            addCriterion("houseid is not null");
            return (Criteria) this;
        }

        public Criteria andHouseidEqualTo(String value) {
            addCriterion("houseid =", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotEqualTo(String value) {
            addCriterion("houseid <>", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidGreaterThan(String value) {
            addCriterion("houseid >", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidGreaterThanOrEqualTo(String value) {
            addCriterion("houseid >=", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidLessThan(String value) {
            addCriterion("houseid <", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidLessThanOrEqualTo(String value) {
            addCriterion("houseid <=", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidLike(String value) {
            addCriterion("houseid like", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotLike(String value) {
            addCriterion("houseid not like", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidIn(List<String> values) {
            addCriterion("houseid in", values, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotIn(List<String> values) {
            addCriterion("houseid not in", values, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidBetween(String value1, String value2) {
            addCriterion("houseid between", value1, value2, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotBetween(String value1, String value2) {
            addCriterion("houseid not between", value1, value2, "houseid");
            return (Criteria) this;
        }

        public Criteria andRentdateStartIsNull() {
            addCriterion("rentdate_start is null");
            return (Criteria) this;
        }

        public Criteria andRentdateStartIsNotNull() {
            addCriterion("rentdate_start is not null");
            return (Criteria) this;
        }

        public Criteria andRentdateStartEqualTo(Date value) {
            addCriterionForJDBCDate("rentdate_start =", value, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateStartNotEqualTo(Date value) {
            addCriterionForJDBCDate("rentdate_start <>", value, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateStartGreaterThan(Date value) {
            addCriterionForJDBCDate("rentdate_start >", value, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateStartGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("rentdate_start >=", value, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateStartLessThan(Date value) {
            addCriterionForJDBCDate("rentdate_start <", value, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateStartLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("rentdate_start <=", value, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateStartIn(List<Date> values) {
            addCriterionForJDBCDate("rentdate_start in", values, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateStartNotIn(List<Date> values) {
            addCriterionForJDBCDate("rentdate_start not in", values, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateStartBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("rentdate_start between", value1, value2, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateStartNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("rentdate_start not between", value1, value2, "rentdateStart");
            return (Criteria) this;
        }

        public Criteria andRentdateEndIsNull() {
            addCriterion("rentdate_end is null");
            return (Criteria) this;
        }

        public Criteria andRentdateEndIsNotNull() {
            addCriterion("rentdate_end is not null");
            return (Criteria) this;
        }

        public Criteria andRentdateEndEqualTo(Date value) {
            addCriterionForJDBCDate("rentdate_end =", value, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentdateEndNotEqualTo(Date value) {
            addCriterionForJDBCDate("rentdate_end <>", value, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentdateEndGreaterThan(Date value) {
            addCriterionForJDBCDate("rentdate_end >", value, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentdateEndGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("rentdate_end >=", value, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentdateEndLessThan(Date value) {
            addCriterionForJDBCDate("rentdate_end <", value, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentdateEndLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("rentdate_end <=", value, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentdateEndIn(List<Date> values) {
            addCriterionForJDBCDate("rentdate_end in", values, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentdateEndNotIn(List<Date> values) {
            addCriterionForJDBCDate("rentdate_end not in", values, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentdateEndBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("rentdate_end between", value1, value2, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentdateEndNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("rentdate_end not between", value1, value2, "rentdateEnd");
            return (Criteria) this;
        }

        public Criteria andRentvalueIsNull() {
            addCriterion("rentvalue is null");
            return (Criteria) this;
        }

        public Criteria andRentvalueIsNotNull() {
            addCriterion("rentvalue is not null");
            return (Criteria) this;
        }

        public Criteria andRentvalueEqualTo(Float value) {
            addCriterion("rentvalue =", value, "rentvalue");
            return (Criteria) this;
        }

        public Criteria andRentvalueNotEqualTo(Float value) {
            addCriterion("rentvalue <>", value, "rentvalue");
            return (Criteria) this;
        }

        public Criteria andRentvalueGreaterThan(Float value) {
            addCriterion("rentvalue >", value, "rentvalue");
            return (Criteria) this;
        }

        public Criteria andRentvalueGreaterThanOrEqualTo(Float value) {
            addCriterion("rentvalue >=", value, "rentvalue");
            return (Criteria) this;
        }

        public Criteria andRentvalueLessThan(Float value) {
            addCriterion("rentvalue <", value, "rentvalue");
            return (Criteria) this;
        }

        public Criteria andRentvalueLessThanOrEqualTo(Float value) {
            addCriterion("rentvalue <=", value, "rentvalue");
            return (Criteria) this;
        }

        public Criteria andRentvalueIn(List<Float> values) {
            addCriterion("rentvalue in", values, "rentvalue");
            return (Criteria) this;
        }

        public Criteria andRentvalueNotIn(List<Float> values) {
            addCriterion("rentvalue not in", values, "rentvalue");
            return (Criteria) this;
        }

        public Criteria andRentvalueBetween(Float value1, Float value2) {
            addCriterion("rentvalue between", value1, value2, "rentvalue");
            return (Criteria) this;
        }

        public Criteria andRentvalueNotBetween(Float value1, Float value2) {
            addCriterion("rentvalue not between", value1, value2, "rentvalue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rentlist
     *
     * @mbg.generated do_not_delete_during_merge Mon May 27 17:56:13 JST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rentlist
     *
     * @mbg.generated Mon May 27 17:56:13 JST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}