package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author admin
 * @date 2024/03/24 10:49:23
 * student 学生テーブル
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TStudent implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated Sun Mar 24 10:49:24 JST 2024
     */
    /**
     * @TableNamestudent
     * @TableRemarks 学生テーブル
     * @ActualColumnName student_id
     * @ActualColumnRemarks id
     * @ActualTypeName INT
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbg.generated Sun Mar 24 10:49:24 JST 2024
     */
    /**
     * @TableNamestudent
     * @TableRemarks 学生テーブル
     * @ActualColumnName student_name
     * @ActualColumnRemarks 学生の名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 255
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_pwd
     *
     * @mbg.generated Sun Mar 24 10:49:24 JST 2024
     */
    /**
     * @TableNamestudent
     * @TableRemarks 学生テーブル
     * @ActualColumnName student_pwd
     * @ActualColumnRemarks 学生の暗証番号
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 255
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String studentPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birthdate
     *
     * @mbg.generated Sun Mar 24 10:49:24 JST 2024
     */
    /**
     * @TableNamestudent
     * @TableRemarks 学生テーブル
     * @ActualColumnName birthdate
     * @ActualColumnRemarks 学生の誕生日
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbg.generated Sun Mar 24 10:49:24 JST 2024
     */
    /**
     * @TableNamestudent
     * @TableRemarks 学生テーブル
     * @ActualColumnName email
     * @ActualColumnRemarks 学生のメールアドレス
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 255
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String email;
}