package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author admin
 * @date 2024/08/04 17:31:22
 * TEACHER teacher talbe
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TTeacher implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.id
     *
     * @mbg.generated Sun Aug 04 17:31:22 JST 2024
     */
    /**
     * @TableNameTEACHER
     * @TableRemarks teacher talbe
     * @ActualColumnName id
     * @ActualColumnRemarks NO
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.name
     *
     * @mbg.generated Sun Aug 04 17:31:22 JST 2024
     */
    /**
     * @TableNameTEACHER
     * @TableRemarks teacher talbe
     * @ActualColumnName name
     * @ActualColumnRemarks my name
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 60
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.salary
     *
     * @mbg.generated Sun Aug 04 17:31:22 JST 2024
     */
    /**
     * @TableNameTEACHER
     * @TableRemarks teacher talbe
     * @ActualColumnName salary
     * @ActualColumnRemarks my salary
     * @ActualTypeName INT
     * @isNullable true
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.birthday
     *
     * @mbg.generated Sun Aug 04 17:31:22 JST 2024
     */
    /**
     * @TableNameTEACHER
     * @TableRemarks teacher talbe
     * @ActualColumnName birthday
     * @ActualColumnRemarks my birthday
     * @ActualTypeName DATETIME
     * @isNullable true
     * @Length 19
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName TIMESTAMP
     * @JdbcType 93
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.sex
     *
     * @mbg.generated Sun Aug 04 17:31:22 JST 2024
     */
    /**
     * @TableNameTEACHER
     * @TableRemarks teacher talbe
     * @ActualColumnName sex
     * @ActualColumnRemarks my sex
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 2
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String sex;
}