package com.baizhi.entity.original;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author user
 * @date 2023/10/03/01:01
 * t_files 文件上传下载
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserFile implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.id
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.old_file_name
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String oldFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.new_file_name
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String newFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.ext
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String ext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.path
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.size
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.type
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.is_img
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String isImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.downcounts
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private Integer downcounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.username
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.delete_flg
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.create_time
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.create_user_id
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.update_time
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_files.update_user_id
     *
     * @mbg.generated Tue Oct 03 13:01:33 JST 2023
     */
    private String updateUserId;
}