package com.baizhi.entity.original;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

/**
 * @author USER
 * @date 2024/09/01 17:17:11
 * zoo animal
 */
@Accessors(chain = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Zoo implements java.io.Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zoo.id
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    /**
     * @TableNamezoo
     * @TableRemarks animal
     * @ActualColumnName id
     * @ActualColumnRemarks NO
     * @ActualTypeName INT UNSIGNED
     * @isNullable false
     * @Length 10
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement true
     * @isIdentity false
     * @isStringColumn false
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName INTEGER
     * @JdbcType 4
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zoo.name
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    /**
     * @TableNamezoo
     * @TableRemarks animal
     * @ActualColumnName name
     * @ActualColumnRemarks 名前
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 60
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zoo.time_feeding
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    /**
     * @TableNamezoo
     * @TableRemarks animal
     * @ActualColumnName time_feeding
     * @ActualColumnRemarks 給food
     * @ActualTypeName CHAR
     * @isNullable true
     * @Length 14
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName CHAR
     * @JdbcType 1
     */
    private String timeFeeding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zoo.food
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    /**
     * @TableNamezoo
     * @TableRemarks animal
     * @ActualColumnName food
     * @ActualColumnRemarks food
     * @ActualTypeName VARCHAR
     * @isNullable true
     * @Length 60
     * @Scale 0
     * @DefaultValue null
     * @isAutoIncrement false
     * @isIdentity false
     * @isStringColumn true
     * @isBLOBColumn false
     * @isJDBCDateColumn false
     * @isJDBCTimeColumn false
     * @JdbcTypeName VARCHAR
     * @JdbcType 12
     */
    private String food;
}