package com.baizhi.dao.original;

import com.baizhi.entity.original.Akibaheadoffice;
import com.baizhi.entity.original.AkibaheadofficeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AkibaheadofficeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    long countByExample(AkibaheadofficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    int deleteByExample(AkibaheadofficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    int insert(Akibaheadoffice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    int insertSelective(Akibaheadoffice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    List<Akibaheadoffice> selectByExample(AkibaheadofficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    Akibaheadoffice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    int updateByExampleSelective(@Param("row") Akibaheadoffice row, @Param("example") AkibaheadofficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    int updateByExample(@Param("row") Akibaheadoffice row, @Param("example") AkibaheadofficeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    int updateByPrimaryKeySelective(Akibaheadoffice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table akibaheadoffice
     *
     * @mbg.generated Sun May 19 13:57:47 JST 2024
     */
    int updateByPrimaryKey(Akibaheadoffice row);
}