package com.baizhi.dao.original;

import com.baizhi.entity.original.Books;
import com.baizhi.entity.original.BooksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BooksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    long countByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int deleteByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int insert(Books row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int insertSelective(Books row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    List<Books> selectByExample(BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    Books selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int updateByExampleSelective(@Param("row") Books row, @Param("example") BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int updateByExample(@Param("row") Books row, @Param("example") BooksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int updateByPrimaryKeySelective(Books row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int updateByPrimaryKey(Books row);
}