package com.baizhi.dao.original;

import com.baizhi.entity.original.Carinfo;
import com.baizhi.entity.original.CarinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    long countByExample(CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int deleteByExample(CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int insert(Carinfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int insertSelective(Carinfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    List<Carinfo> selectByExample(CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    Carinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int updateByExampleSelective(@Param("row") Carinfo row, @Param("example") CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int updateByExample(@Param("row") Carinfo row, @Param("example") CarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int updateByPrimaryKeySelective(Carinfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated Sun Nov 12 11:55:54 JST 2023
     */
    int updateByPrimaryKey(Carinfo row);
}