package com.baizhi.dao.original;

import com.baizhi.entity.original.MCode;
import com.baizhi.entity.original.MCodeExample;
import com.baizhi.entity.original.MCodeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    long countByExample(MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int deleteByExample(MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int deleteByPrimaryKey(MCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int insert(MCode row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int insertSelective(MCode row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    List<MCode> selectByExample(MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    MCode selectByPrimaryKey(MCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int updateByExampleSelective(@Param("row") MCode row, @Param("example") MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int updateByExample(@Param("row") MCode row, @Param("example") MCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int updateByPrimaryKeySelective(MCode row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_code
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int updateByPrimaryKey(MCode row);
}