package com.baizhi.dao.original;

import com.baizhi.entity.original.MDensya;
import com.baizhi.entity.original.MDensyaExample;
import com.baizhi.entity.original.MDensyaKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MDensyaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    long countByExample(MDensyaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int deleteByExample(MDensyaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int deleteByPrimaryKey(MDensyaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int insert(MDensya row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int insertSelective(MDensya row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    List<MDensya> selectByExample(MDensyaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    MDensya selectByPrimaryKey(MDensyaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int updateByExampleSelective(@Param("row") MDensya row, @Param("example") MDensyaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int updateByExample(@Param("row") MDensya row, @Param("example") MDensyaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int updateByPrimaryKeySelective(MDensya row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya
     *
     * @mbg.generated Sat Jan 11 15:46:15 JST 2025
     */
    int updateByPrimaryKey(MDensya row);
}