package com.baizhi.dao.original;

import com.baizhi.entity.original.MDensyaEki;
import com.baizhi.entity.original.MDensyaEkiExample;
import com.baizhi.entity.original.MDensyaEkiKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MDensyaEkiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    long countByExample(MDensyaEkiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    int deleteByExample(MDensyaEkiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    int deleteByPrimaryKey(MDensyaEkiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    int insert(MDensyaEki row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    int insertSelective(MDensyaEki row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    List<MDensyaEki> selectByExample(MDensyaEkiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    MDensyaEki selectByPrimaryKey(MDensyaEkiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    int updateByExampleSelective(@Param("row") MDensyaEki row, @Param("example") MDensyaEkiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    int updateByExample(@Param("row") MDensyaEki row, @Param("example") MDensyaEkiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    int updateByPrimaryKeySelective(MDensyaEki row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_densya_eki
     *
     * @mbg.generated Thu Dec 26 23:54:00 JST 2024
     */
    int updateByPrimaryKey(MDensyaEki row);
}