package com.baizhi.dao.original;

import com.baizhi.entity.original.Mytruck;
import com.baizhi.entity.original.MytruckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MytruckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    long countByExample(MytruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    int deleteByExample(MytruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    int insert(Mytruck row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    int insertSelective(Mytruck row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    List<Mytruck> selectByExample(MytruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    Mytruck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    int updateByExampleSelective(@Param("row") Mytruck row, @Param("example") MytruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    int updateByExample(@Param("row") Mytruck row, @Param("example") MytruckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    int updateByPrimaryKeySelective(Mytruck row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mytruck
     *
     * @mbg.generated Thu Feb 08 18:45:15 JST 2024
     */
    int updateByPrimaryKey(Mytruck row);
}