package com.baizhi.dao.original;

import com.baizhi.entity.original.Oucompany;
import com.baizhi.entity.original.OucompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OucompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    long countByExample(OucompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    int deleteByExample(OucompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    int insert(Oucompany row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    int insertSelective(Oucompany row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    List<Oucompany> selectByExample(OucompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    Oucompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    int updateByExampleSelective(@Param("row") Oucompany row, @Param("example") OucompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    int updateByExample(@Param("row") Oucompany row, @Param("example") OucompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    int updateByPrimaryKeySelective(Oucompany row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Oucompany
     *
     * @mbg.generated Sun May 19 17:02:36 JST 2024
     */
    int updateByPrimaryKey(Oucompany row);
}