package com.baizhi.dao.original;

import com.baizhi.entity.original.Senmongakusei;
import com.baizhi.entity.original.SenmongakuseiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SenmongakuseiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    long countByExample(SenmongakuseiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int deleteByExample(SenmongakuseiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int insert(Senmongakusei row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int insertSelective(Senmongakusei row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    List<Senmongakusei> selectByExample(SenmongakuseiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    Senmongakusei selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int updateByExampleSelective(@Param("row") Senmongakusei row, @Param("example") SenmongakuseiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int updateByExample(@Param("row") Senmongakusei row, @Param("example") SenmongakuseiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int updateByPrimaryKeySelective(Senmongakusei row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table senmongakusei
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int updateByPrimaryKey(Senmongakusei row);
}