package com.baizhi.dao.original;

import com.baizhi.entity.original.TBuken;
import com.baizhi.entity.original.TBukenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBukenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    long countByExample(TBukenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    int deleteByExample(TBukenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    int deleteByPrimaryKey(Integer bukenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    int insert(TBuken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    int insertSelective(TBuken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    List<TBuken> selectByExample(TBukenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    TBuken selectByPrimaryKey(Integer bukenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    int updateByExampleSelective(@Param("row") TBuken row, @Param("example") TBukenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    int updateByExample(@Param("row") TBuken row, @Param("example") TBukenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    int updateByPrimaryKeySelective(TBuken row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken
     *
     * @mbg.generated Mon Nov 25 11:31:52 CST 2024
     */
    int updateByPrimaryKey(TBuken row);
}