package com.baizhi.dao.original;

import com.baizhi.entity.original.TBukenIcon;
import com.baizhi.entity.original.TBukenIconExample;
import com.baizhi.entity.original.TBukenIconKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBukenIconMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    long countByExample(TBukenIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int deleteByExample(TBukenIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int deleteByPrimaryKey(TBukenIconKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int insert(TBukenIcon row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int insertSelective(TBukenIcon row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    List<TBukenIcon> selectByExample(TBukenIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    TBukenIcon selectByPrimaryKey(TBukenIconKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int updateByExampleSelective(@Param("row") TBukenIcon row, @Param("example") TBukenIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int updateByExample(@Param("row") TBukenIcon row, @Param("example") TBukenIconExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int updateByPrimaryKeySelective(TBukenIcon row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buken_icon
     *
     * @mbg.generated Sat Jan 18 16:23:43 JST 2025
     */
    int updateByPrimaryKey(TBukenIcon row);
}