package com.baizhi.dao.original;

import com.baizhi.entity.original.TFruit;
import com.baizhi.entity.original.TFruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    long countByExample(TFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    int deleteByExample(TFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    int insert(TFruit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    int insertSelective(TFruit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    List<TFruit> selectByExample(TFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    TFruit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    int updateByExampleSelective(@Param("row") TFruit row, @Param("example") TFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    int updateByExample(@Param("row") TFruit row, @Param("example") TFruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    int updateByPrimaryKeySelective(TFruit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbg.generated Sun May 12 17:21:01 JST 2024
     */
    int updateByPrimaryKey(TFruit row);
}