package com.baizhi.dao.original;

import com.baizhi.entity.original.THakoneEkidenRanking;
import com.baizhi.entity.original.THakoneEkidenRankingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THakoneEkidenRankingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    long countByExample(THakoneEkidenRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    int deleteByExample(THakoneEkidenRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    int insert(THakoneEkidenRanking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    int insertSelective(THakoneEkidenRanking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    List<THakoneEkidenRanking> selectByExample(THakoneEkidenRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    THakoneEkidenRanking selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    int updateByExampleSelective(@Param("row") THakoneEkidenRanking row, @Param("example") THakoneEkidenRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    int updateByExample(@Param("row") THakoneEkidenRanking row, @Param("example") THakoneEkidenRankingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    int updateByPrimaryKeySelective(THakoneEkidenRanking row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hakoneekidenranking
     *
     * @mbg.generated Sun Mar 24 12:48:14 JST 2024
     */
    int updateByPrimaryKey(THakoneEkidenRanking row);
}