package com.baizhi.dao.original;

import com.baizhi.entity.original.TokyoMetro1;
import com.baizhi.entity.original.TokyoMetro1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TokyoMetro1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    long countByExample(TokyoMetro1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    int deleteByExample(TokyoMetro1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    int insert(TokyoMetro1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    int insertSelective(TokyoMetro1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    List<TokyoMetro1> selectByExample(TokyoMetro1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    TokyoMetro1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    int updateByExampleSelective(@Param("row") TokyoMetro1 row, @Param("example") TokyoMetro1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    int updateByExample(@Param("row") TokyoMetro1 row, @Param("example") TokyoMetro1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    int updateByPrimaryKeySelective(TokyoMetro1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TokyoMetro1
     *
     * @mbg.generated Sun May 12 13:58:15 JST 2024
     */
    int updateByPrimaryKey(TokyoMetro1 row);
}