package com.baizhi.dao.original;

import com.baizhi.entity.original.Uniqlo;
import com.baizhi.entity.original.UniqloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UniqloMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    long countByExample(UniqloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int deleteByExample(UniqloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int insert(Uniqlo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int insertSelective(Uniqlo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    List<Uniqlo> selectByExampleWithBLOBs(UniqloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    List<Uniqlo> selectByExample(UniqloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    Uniqlo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int updateByExampleSelective(@Param("row") Uniqlo row, @Param("example") UniqloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") Uniqlo row, @Param("example") UniqloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int updateByExample(@Param("row") Uniqlo row, @Param("example") UniqloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int updateByPrimaryKeySelective(Uniqlo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Uniqlo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uniqlo
     *
     * @mbg.generated Fri Nov 10 23:50:57 JST 2023
     */
    int updateByPrimaryKey(Uniqlo row);
}