package com.baizhi.dao.original;

import com.baizhi.entity.original.Zoo;
import com.baizhi.entity.original.ZooExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZooMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    long countByExample(ZooExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    int deleteByExample(ZooExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    int insert(Zoo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    int insertSelective(Zoo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    List<Zoo> selectByExample(ZooExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    Zoo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    int updateByExampleSelective(@Param("row") Zoo row, @Param("example") ZooExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    int updateByExample(@Param("row") Zoo row, @Param("example") ZooExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    int updateByPrimaryKeySelective(Zoo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zoo
     *
     * @mbg.generated Sun Sep 01 17:17:11 JST 2024
     */
    int updateByPrimaryKey(Zoo row);
}