server:
  port: 9999
  servlet:
    context-path: /ems-thymeleaf





spring:

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems-thymeleaf?characterEncoding=UTF-8
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:/static/,file:${photo.file.dir} 




mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity


logging:
  level:
    root: info
    com.baizhi: debug



photo:
  file:
    dir: /Users/chenyn/Desktop/线上课/项目阶段/01springboot/codes/ems-thymeleaf/photos

